
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

squash: true

deep-remove-regex:
    - /owl-bot-staging

deep-copy-regex:
    - source: /google/cloud/location/.*-csharp/Google.Cloud.Location
      dest: /owl-bot-staging/Google.Cloud.Location/Google.Cloud.Location
    - source: /google/cloud/location/.*-csharp/Google.Cloud.Location.Snippets
      dest: /owl-bot-staging/Google.Cloud.Location/Google.Cloud.Location.Snippets
    - source: /google/cloud/location/.*-csharp/Google.Cloud.Location.GeneratedSnippets
      dest: /owl-bot-staging/Google.Cloud.Location/Google.Cloud.Location.GeneratedSnippets
    - source: /google/cloud/location/.*-csharp/gapic_metadata.json
      dest: /owl-bot-staging/Google.Cloud.Location/gapic_metadata.json

api-name: Google.Cloud.Location
