// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/cloud/aiplatform/v1/data_foundry_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Cloud.AIPlatform.V1 {

  /// <summary>Holder for reflection information generated from google/cloud/aiplatform/v1/data_foundry_service.proto</summary>
  public static partial class DataFoundryServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for google/cloud/aiplatform/v1/data_foundry_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DataFoundryServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVnb29nbGUvY2xvdWQvYWlwbGF0Zm9ybS92MS9kYXRhX2ZvdW5kcnlfc2Vy",
            "dmljZS5wcm90bxIaZ29vZ2xlLmNsb3VkLmFpcGxhdGZvcm0udjEaHGdvb2ds",
            "ZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8aF2dvb2dsZS9hcGkvY2xpZW50LnBy",
            "b3RvGh9nb29nbGUvYXBpL2ZpZWxkX2JlaGF2aW9yLnByb3RvGhlnb29nbGUv",
            "YXBpL3Jlc291cmNlLnByb3RvGihnb29nbGUvY2xvdWQvYWlwbGF0Zm9ybS92",
            "MS9jb250ZW50LnByb3RvIt8CChxHZW5lcmF0ZVN5bnRoZXRpY0RhdGFSZXF1",
            "ZXN0Ek8KEHRhc2tfZGVzY3JpcHRpb24YAyABKAsyMy5nb29nbGUuY2xvdWQu",
            "YWlwbGF0Zm9ybS52MS5UYXNrRGVzY3JpcHRpb25TdHJhdGVneUgAEjsKCGxv",
            "Y2F0aW9uGAEgASgJQingQQL6QSMKIWxvY2F0aW9ucy5nb29nbGVhcGlzLmNv",
            "bS9Mb2NhdGlvbhISCgVjb3VudBgCIAEoBUID4EECEkwKEm91dHB1dF9maWVs",
            "ZF9zcGVjcxgEIAMoCzIrLmdvb2dsZS5jbG91ZC5haXBsYXRmb3JtLnYxLk91",
            "dHB1dEZpZWxkU3BlY0ID4EECEkMKCGV4YW1wbGVzGAUgAygLMiwuZ29vZ2xl",
            "LmNsb3VkLmFpcGxhdGZvcm0udjEuU3ludGhldGljRXhhbXBsZUID4EEBQgoK",
            "CHN0cmF0ZWd5ImQKDlN5bnRoZXRpY0ZpZWxkEhcKCmZpZWxkX25hbWUYASAB",
            "KAlCA+BBARI5Cgdjb250ZW50GAIgASgLMiMuZ29vZ2xlLmNsb3VkLmFpcGxh",
            "dGZvcm0udjEuQ29udGVudEID4EECIlMKEFN5bnRoZXRpY0V4YW1wbGUSPwoG",
            "ZmllbGRzGAEgAygLMiouZ29vZ2xlLmNsb3VkLmFpcGxhdGZvcm0udjEuU3lu",
            "dGhldGljRmllbGRCA+BBAiLnAQoPT3V0cHV0RmllbGRTcGVjEhcKCmZpZWxk",
            "X25hbWUYASABKAlCA+BBAhIVCghndWlkYW5jZRgCIAEoCUID4EEBEk4KCmZp",
            "ZWxkX3R5cGUYAyABKA4yNS5nb29nbGUuY2xvdWQuYWlwbGF0Zm9ybS52MS5P",
            "dXRwdXRGaWVsZFNwZWMuRmllbGRUeXBlQgPgQQEiVAoJRmllbGRUeXBlEhoK",
            "FkZJRUxEX1RZUEVfVU5TUEVDSUZJRUQQABILCgdDT05URU5UEAESCAoEVEVY",
            "VBACEgkKBUlNQUdFEAMSCQoFQVVESU8QBCI4ChdUYXNrRGVzY3JpcHRpb25T",
            "dHJhdGVneRIdChB0YXNrX2Rlc2NyaXB0aW9uGAEgASgJQgPgQQIiaQodR2Vu",
            "ZXJhdGVTeW50aGV0aWNEYXRhUmVzcG9uc2USSAoSc3ludGhldGljX2V4YW1w",
            "bGVzGAEgAygLMiwuZ29vZ2xlLmNsb3VkLmFpcGxhdGZvcm0udjEuU3ludGhl",
            "dGljRXhhbXBsZTK6AgoSRGF0YUZvdW5kcnlTZXJ2aWNlEtQBChVHZW5lcmF0",
            "ZVN5bnRoZXRpY0RhdGESOC5nb29nbGUuY2xvdWQuYWlwbGF0Zm9ybS52MS5H",
            "ZW5lcmF0ZVN5bnRoZXRpY0RhdGFSZXF1ZXN0GjkuZ29vZ2xlLmNsb3VkLmFp",
            "cGxhdGZvcm0udjEuR2VuZXJhdGVTeW50aGV0aWNEYXRhUmVzcG9uc2UiRoLT",
            "5JMCQCI7L3YxL3tsb2NhdGlvbj1wcm9qZWN0cy8qL2xvY2F0aW9ucy8qfTpn",
            "ZW5lcmF0ZVN5bnRoZXRpY0RhdGE6ASoaTcpBGWFpcGxhdGZvcm0uZ29vZ2xl",
            "YXBpcy5jb23SQS5odHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2Ns",
            "b3VkLXBsYXRmb3JtQtUBCh5jb20uZ29vZ2xlLmNsb3VkLmFpcGxhdGZvcm0u",
            "djFCF0RhdGFGb3VuZHJ5U2VydmljZVByb3RvUAFaPmNsb3VkLmdvb2dsZS5j",
            "b20vZ28vYWlwbGF0Zm9ybS9hcGl2MS9haXBsYXRmb3JtcGI7YWlwbGF0Zm9y",
            "bXBiqgIaR29vZ2xlLkNsb3VkLkFJUGxhdGZvcm0uVjHKAhpHb29nbGVcQ2xv",
            "dWRcQUlQbGF0Zm9ybVxWMeoCHUdvb2dsZTo6Q2xvdWQ6OkFJUGxhdGZvcm06",
            "OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Api.ClientReflection.Descriptor, global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, global::Google.Cloud.AIPlatform.V1.ContentReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.AIPlatform.V1.GenerateSyntheticDataRequest), global::Google.Cloud.AIPlatform.V1.GenerateSyntheticDataRequest.Parser, new[]{ "TaskDescription", "Location", "Count", "OutputFieldSpecs", "Examples" }, new[]{ "Strategy" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.AIPlatform.V1.SyntheticField), global::Google.Cloud.AIPlatform.V1.SyntheticField.Parser, new[]{ "FieldName", "Content" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.AIPlatform.V1.SyntheticExample), global::Google.Cloud.AIPlatform.V1.SyntheticExample.Parser, new[]{ "Fields" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.AIPlatform.V1.OutputFieldSpec), global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Parser, new[]{ "FieldName", "Guidance", "FieldType" }, null, new[]{ typeof(global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.AIPlatform.V1.TaskDescriptionStrategy), global::Google.Cloud.AIPlatform.V1.TaskDescriptionStrategy.Parser, new[]{ "TaskDescription" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.AIPlatform.V1.GenerateSyntheticDataResponse), global::Google.Cloud.AIPlatform.V1.GenerateSyntheticDataResponse.Parser, new[]{ "SyntheticExamples" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Request message for DataFoundryService.GenerateSyntheticData.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GenerateSyntheticDataRequest : pb::IMessage<GenerateSyntheticDataRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GenerateSyntheticDataRequest> _parser = new pb::MessageParser<GenerateSyntheticDataRequest>(() => new GenerateSyntheticDataRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GenerateSyntheticDataRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.AIPlatform.V1.DataFoundryServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateSyntheticDataRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateSyntheticDataRequest(GenerateSyntheticDataRequest other) : this() {
      location_ = other.location_;
      count_ = other.count_;
      outputFieldSpecs_ = other.outputFieldSpecs_.Clone();
      examples_ = other.examples_.Clone();
      switch (other.StrategyCase) {
        case StrategyOneofCase.TaskDescription:
          TaskDescription = other.TaskDescription.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateSyntheticDataRequest Clone() {
      return new GenerateSyntheticDataRequest(this);
    }

    /// <summary>Field number for the "task_description" field.</summary>
    public const int TaskDescriptionFieldNumber = 3;
    /// <summary>
    /// Generate data from a high-level task description.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Cloud.AIPlatform.V1.TaskDescriptionStrategy TaskDescription {
      get { return strategyCase_ == StrategyOneofCase.TaskDescription ? (global::Google.Cloud.AIPlatform.V1.TaskDescriptionStrategy) strategy_ : null; }
      set {
        strategy_ = value;
        strategyCase_ = value == null ? StrategyOneofCase.None : StrategyOneofCase.TaskDescription;
      }
    }

    /// <summary>Field number for the "location" field.</summary>
    public const int LocationFieldNumber = 1;
    private string location_ = "";
    /// <summary>
    /// Required. The resource name of the Location to run the job.
    /// Format: `projects/{project}/locations/{location}`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Location {
      get { return location_; }
      set {
        location_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 2;
    private int count_;
    /// <summary>
    /// Required. The number of synthetic examples to generate.
    /// For this stateless API, the count is limited to a small number.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "output_field_specs" field.</summary>
    public const int OutputFieldSpecsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Google.Cloud.AIPlatform.V1.OutputFieldSpec> _repeated_outputFieldSpecs_codec
        = pb::FieldCodec.ForMessage(34, global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Parser);
    private readonly pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.OutputFieldSpec> outputFieldSpecs_ = new pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.OutputFieldSpec>();
    /// <summary>
    /// Required. The schema of the desired output, defined by a list of fields.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.OutputFieldSpec> OutputFieldSpecs {
      get { return outputFieldSpecs_; }
    }

    /// <summary>Field number for the "examples" field.</summary>
    public const int ExamplesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Google.Cloud.AIPlatform.V1.SyntheticExample> _repeated_examples_codec
        = pb::FieldCodec.ForMessage(42, global::Google.Cloud.AIPlatform.V1.SyntheticExample.Parser);
    private readonly pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.SyntheticExample> examples_ = new pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.SyntheticExample>();
    /// <summary>
    /// Optional. A list of few-shot examples to guide the model's output style
    /// and format.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.SyntheticExample> Examples {
      get { return examples_; }
    }

    private object strategy_;
    /// <summary>Enum of possible cases for the "strategy" oneof.</summary>
    public enum StrategyOneofCase {
      None = 0,
      TaskDescription = 3,
    }
    private StrategyOneofCase strategyCase_ = StrategyOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StrategyOneofCase StrategyCase {
      get { return strategyCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStrategy() {
      strategyCase_ = StrategyOneofCase.None;
      strategy_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GenerateSyntheticDataRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GenerateSyntheticDataRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(TaskDescription, other.TaskDescription)) return false;
      if (Location != other.Location) return false;
      if (Count != other.Count) return false;
      if(!outputFieldSpecs_.Equals(other.outputFieldSpecs_)) return false;
      if(!examples_.Equals(other.examples_)) return false;
      if (StrategyCase != other.StrategyCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (strategyCase_ == StrategyOneofCase.TaskDescription) hash ^= TaskDescription.GetHashCode();
      if (Location.Length != 0) hash ^= Location.GetHashCode();
      if (Count != 0) hash ^= Count.GetHashCode();
      hash ^= outputFieldSpecs_.GetHashCode();
      hash ^= examples_.GetHashCode();
      hash ^= (int) strategyCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Location.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Location);
      }
      if (Count != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Count);
      }
      if (strategyCase_ == StrategyOneofCase.TaskDescription) {
        output.WriteRawTag(26);
        output.WriteMessage(TaskDescription);
      }
      outputFieldSpecs_.WriteTo(output, _repeated_outputFieldSpecs_codec);
      examples_.WriteTo(output, _repeated_examples_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Location.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Location);
      }
      if (Count != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Count);
      }
      if (strategyCase_ == StrategyOneofCase.TaskDescription) {
        output.WriteRawTag(26);
        output.WriteMessage(TaskDescription);
      }
      outputFieldSpecs_.WriteTo(ref output, _repeated_outputFieldSpecs_codec);
      examples_.WriteTo(ref output, _repeated_examples_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (strategyCase_ == StrategyOneofCase.TaskDescription) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TaskDescription);
      }
      if (Location.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Location);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      size += outputFieldSpecs_.CalculateSize(_repeated_outputFieldSpecs_codec);
      size += examples_.CalculateSize(_repeated_examples_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GenerateSyntheticDataRequest other) {
      if (other == null) {
        return;
      }
      if (other.Location.Length != 0) {
        Location = other.Location;
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      outputFieldSpecs_.Add(other.outputFieldSpecs_);
      examples_.Add(other.examples_);
      switch (other.StrategyCase) {
        case StrategyOneofCase.TaskDescription:
          if (TaskDescription == null) {
            TaskDescription = new global::Google.Cloud.AIPlatform.V1.TaskDescriptionStrategy();
          }
          TaskDescription.MergeFrom(other.TaskDescription);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Location = input.ReadString();
            break;
          }
          case 16: {
            Count = input.ReadInt32();
            break;
          }
          case 26: {
            global::Google.Cloud.AIPlatform.V1.TaskDescriptionStrategy subBuilder = new global::Google.Cloud.AIPlatform.V1.TaskDescriptionStrategy();
            if (strategyCase_ == StrategyOneofCase.TaskDescription) {
              subBuilder.MergeFrom(TaskDescription);
            }
            input.ReadMessage(subBuilder);
            TaskDescription = subBuilder;
            break;
          }
          case 34: {
            outputFieldSpecs_.AddEntriesFrom(input, _repeated_outputFieldSpecs_codec);
            break;
          }
          case 42: {
            examples_.AddEntriesFrom(input, _repeated_examples_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Location = input.ReadString();
            break;
          }
          case 16: {
            Count = input.ReadInt32();
            break;
          }
          case 26: {
            global::Google.Cloud.AIPlatform.V1.TaskDescriptionStrategy subBuilder = new global::Google.Cloud.AIPlatform.V1.TaskDescriptionStrategy();
            if (strategyCase_ == StrategyOneofCase.TaskDescription) {
              subBuilder.MergeFrom(TaskDescription);
            }
            input.ReadMessage(subBuilder);
            TaskDescription = subBuilder;
            break;
          }
          case 34: {
            outputFieldSpecs_.AddEntriesFrom(ref input, _repeated_outputFieldSpecs_codec);
            break;
          }
          case 42: {
            examples_.AddEntriesFrom(ref input, _repeated_examples_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Represents a single named field within a SyntheticExample.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SyntheticField : pb::IMessage<SyntheticField>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SyntheticField> _parser = new pb::MessageParser<SyntheticField>(() => new SyntheticField());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SyntheticField> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.AIPlatform.V1.DataFoundryServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SyntheticField() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SyntheticField(SyntheticField other) : this() {
      fieldName_ = other.fieldName_;
      content_ = other.content_ != null ? other.content_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SyntheticField Clone() {
      return new SyntheticField(this);
    }

    /// <summary>Field number for the "field_name" field.</summary>
    public const int FieldNameFieldNumber = 1;
    private string fieldName_ = "";
    /// <summary>
    /// Optional. The name of the field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FieldName {
      get { return fieldName_; }
      set {
        fieldName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 2;
    private global::Google.Cloud.AIPlatform.V1.Content content_;
    /// <summary>
    /// Required. The content of the field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Cloud.AIPlatform.V1.Content Content {
      get { return content_; }
      set {
        content_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SyntheticField);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SyntheticField other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FieldName != other.FieldName) return false;
      if (!object.Equals(Content, other.Content)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FieldName.Length != 0) hash ^= FieldName.GetHashCode();
      if (content_ != null) hash ^= Content.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FieldName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FieldName);
      }
      if (content_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Content);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FieldName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FieldName);
      }
      if (content_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Content);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FieldName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FieldName);
      }
      if (content_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Content);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SyntheticField other) {
      if (other == null) {
        return;
      }
      if (other.FieldName.Length != 0) {
        FieldName = other.FieldName;
      }
      if (other.content_ != null) {
        if (content_ == null) {
          Content = new global::Google.Cloud.AIPlatform.V1.Content();
        }
        Content.MergeFrom(other.Content);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FieldName = input.ReadString();
            break;
          }
          case 18: {
            if (content_ == null) {
              Content = new global::Google.Cloud.AIPlatform.V1.Content();
            }
            input.ReadMessage(Content);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FieldName = input.ReadString();
            break;
          }
          case 18: {
            if (content_ == null) {
              Content = new global::Google.Cloud.AIPlatform.V1.Content();
            }
            input.ReadMessage(Content);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Represents a single synthetic example, composed of multiple fields.
  /// Used for providing few-shot examples in the request and for returning
  /// generated examples in the response.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SyntheticExample : pb::IMessage<SyntheticExample>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SyntheticExample> _parser = new pb::MessageParser<SyntheticExample>(() => new SyntheticExample());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SyntheticExample> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.AIPlatform.V1.DataFoundryServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SyntheticExample() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SyntheticExample(SyntheticExample other) : this() {
      fields_ = other.fields_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SyntheticExample Clone() {
      return new SyntheticExample(this);
    }

    /// <summary>Field number for the "fields" field.</summary>
    public const int FieldsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Google.Cloud.AIPlatform.V1.SyntheticField> _repeated_fields_codec
        = pb::FieldCodec.ForMessage(10, global::Google.Cloud.AIPlatform.V1.SyntheticField.Parser);
    private readonly pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.SyntheticField> fields_ = new pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.SyntheticField>();
    /// <summary>
    /// Required. A list of fields that constitute an example.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.SyntheticField> Fields {
      get { return fields_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SyntheticExample);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SyntheticExample other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!fields_.Equals(other.fields_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= fields_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      fields_.WriteTo(output, _repeated_fields_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      fields_.WriteTo(ref output, _repeated_fields_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += fields_.CalculateSize(_repeated_fields_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SyntheticExample other) {
      if (other == null) {
        return;
      }
      fields_.Add(other.fields_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            fields_.AddEntriesFrom(input, _repeated_fields_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            fields_.AddEntriesFrom(ref input, _repeated_fields_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Defines a specification for a single output field.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OutputFieldSpec : pb::IMessage<OutputFieldSpec>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OutputFieldSpec> _parser = new pb::MessageParser<OutputFieldSpec>(() => new OutputFieldSpec());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OutputFieldSpec> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.AIPlatform.V1.DataFoundryServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OutputFieldSpec() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OutputFieldSpec(OutputFieldSpec other) : this() {
      fieldName_ = other.fieldName_;
      guidance_ = other.guidance_;
      fieldType_ = other.fieldType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OutputFieldSpec Clone() {
      return new OutputFieldSpec(this);
    }

    /// <summary>Field number for the "field_name" field.</summary>
    public const int FieldNameFieldNumber = 1;
    private string fieldName_ = "";
    /// <summary>
    /// Required. The name of the output field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FieldName {
      get { return fieldName_; }
      set {
        fieldName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "guidance" field.</summary>
    public const int GuidanceFieldNumber = 2;
    private string guidance_ = "";
    /// <summary>
    /// Optional. Optional, but recommended. Additional guidance specific to this
    /// field to provide targeted instructions for the LLM to generate the content
    /// of a single output field. While the LLM can sometimes infer content from
    /// the field name, providing explicit guidance is preferred.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Guidance {
      get { return guidance_; }
      set {
        guidance_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "field_type" field.</summary>
    public const int FieldTypeFieldNumber = 3;
    private global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType fieldType_ = global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType.Unspecified;
    /// <summary>
    /// Optional. The data type of the field. Defaults to CONTENT if not set.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType FieldType {
      get { return fieldType_; }
      set {
        fieldType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OutputFieldSpec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OutputFieldSpec other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FieldName != other.FieldName) return false;
      if (Guidance != other.Guidance) return false;
      if (FieldType != other.FieldType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FieldName.Length != 0) hash ^= FieldName.GetHashCode();
      if (Guidance.Length != 0) hash ^= Guidance.GetHashCode();
      if (FieldType != global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType.Unspecified) hash ^= FieldType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FieldName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FieldName);
      }
      if (Guidance.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Guidance);
      }
      if (FieldType != global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) FieldType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FieldName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FieldName);
      }
      if (Guidance.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Guidance);
      }
      if (FieldType != global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) FieldType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FieldName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FieldName);
      }
      if (Guidance.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Guidance);
      }
      if (FieldType != global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FieldType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OutputFieldSpec other) {
      if (other == null) {
        return;
      }
      if (other.FieldName.Length != 0) {
        FieldName = other.FieldName;
      }
      if (other.Guidance.Length != 0) {
        Guidance = other.Guidance;
      }
      if (other.FieldType != global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType.Unspecified) {
        FieldType = other.FieldType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FieldName = input.ReadString();
            break;
          }
          case 18: {
            Guidance = input.ReadString();
            break;
          }
          case 24: {
            FieldType = (global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FieldName = input.ReadString();
            break;
          }
          case 18: {
            Guidance = input.ReadString();
            break;
          }
          case 24: {
            FieldType = (global::Google.Cloud.AIPlatform.V1.OutputFieldSpec.Types.FieldType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the OutputFieldSpec message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// The data type of the field.
      /// </summary>
      public enum FieldType {
        /// <summary>
        /// Field type is unspecified.
        /// </summary>
        [pbr::OriginalName("FIELD_TYPE_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// Arbitrary content field type.
        /// </summary>
        [pbr::OriginalName("CONTENT")] Content = 1,
        /// <summary>
        /// Text field type.
        /// </summary>
        [pbr::OriginalName("TEXT")] Text = 2,
        /// <summary>
        /// Image field type.
        /// </summary>
        [pbr::OriginalName("IMAGE")] Image = 3,
        /// <summary>
        /// Audio field type.
        /// </summary>
        [pbr::OriginalName("AUDIO")] Audio = 4,
      }

    }
    #endregion

  }

  /// <summary>
  /// Defines a generation strategy based on a high-level task description.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TaskDescriptionStrategy : pb::IMessage<TaskDescriptionStrategy>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaskDescriptionStrategy> _parser = new pb::MessageParser<TaskDescriptionStrategy>(() => new TaskDescriptionStrategy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaskDescriptionStrategy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.AIPlatform.V1.DataFoundryServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskDescriptionStrategy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskDescriptionStrategy(TaskDescriptionStrategy other) : this() {
      taskDescription_ = other.taskDescription_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaskDescriptionStrategy Clone() {
      return new TaskDescriptionStrategy(this);
    }

    /// <summary>Field number for the "task_description" field.</summary>
    public const int TaskDescriptionFieldNumber = 1;
    private string taskDescription_ = "";
    /// <summary>
    /// Required. A high-level description of the synthetic data to be generated.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaskDescription {
      get { return taskDescription_; }
      set {
        taskDescription_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaskDescriptionStrategy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaskDescriptionStrategy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaskDescription != other.TaskDescription) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TaskDescription.Length != 0) hash ^= TaskDescription.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TaskDescription.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TaskDescription);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TaskDescription.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TaskDescription);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TaskDescription.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskDescription);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaskDescriptionStrategy other) {
      if (other == null) {
        return;
      }
      if (other.TaskDescription.Length != 0) {
        TaskDescription = other.TaskDescription;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TaskDescription = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TaskDescription = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The response containing the generated data.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GenerateSyntheticDataResponse : pb::IMessage<GenerateSyntheticDataResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GenerateSyntheticDataResponse> _parser = new pb::MessageParser<GenerateSyntheticDataResponse>(() => new GenerateSyntheticDataResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GenerateSyntheticDataResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.AIPlatform.V1.DataFoundryServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateSyntheticDataResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateSyntheticDataResponse(GenerateSyntheticDataResponse other) : this() {
      syntheticExamples_ = other.syntheticExamples_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GenerateSyntheticDataResponse Clone() {
      return new GenerateSyntheticDataResponse(this);
    }

    /// <summary>Field number for the "synthetic_examples" field.</summary>
    public const int SyntheticExamplesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Google.Cloud.AIPlatform.V1.SyntheticExample> _repeated_syntheticExamples_codec
        = pb::FieldCodec.ForMessage(10, global::Google.Cloud.AIPlatform.V1.SyntheticExample.Parser);
    private readonly pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.SyntheticExample> syntheticExamples_ = new pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.SyntheticExample>();
    /// <summary>
    /// A list of generated synthetic examples.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Cloud.AIPlatform.V1.SyntheticExample> SyntheticExamples {
      get { return syntheticExamples_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GenerateSyntheticDataResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GenerateSyntheticDataResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!syntheticExamples_.Equals(other.syntheticExamples_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= syntheticExamples_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      syntheticExamples_.WriteTo(output, _repeated_syntheticExamples_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      syntheticExamples_.WriteTo(ref output, _repeated_syntheticExamples_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += syntheticExamples_.CalculateSize(_repeated_syntheticExamples_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GenerateSyntheticDataResponse other) {
      if (other == null) {
        return;
      }
      syntheticExamples_.Add(other.syntheticExamples_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            syntheticExamples_.AddEntriesFrom(input, _repeated_syntheticExamples_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            syntheticExamples_.AddEntriesFrom(ref input, _repeated_syntheticExamples_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
