// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/cloud/orgpolicy/v2/constraint.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Cloud.OrgPolicy.V2 {

  /// <summary>Holder for reflection information generated from google/cloud/orgpolicy/v2/constraint.proto</summary>
  public static partial class ConstraintReflection {

    #region Descriptor
    /// <summary>File descriptor for google/cloud/orgpolicy/v2/constraint.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConstraintReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cipnb29nbGUvY2xvdWQvb3JncG9saWN5L3YyL2NvbnN0cmFpbnQucHJvdG8S",
            "GWdvb2dsZS5jbG91ZC5vcmdwb2xpY3kudjIaH2dvb2dsZS9hcGkvZmllbGRf",
            "YmVoYXZpb3IucHJvdG8aGWdvb2dsZS9hcGkvcmVzb3VyY2UucHJvdG8itwUK",
            "CkNvbnN0cmFpbnQSEQoEbmFtZRgBIAEoCUID4EEFEhQKDGRpc3BsYXlfbmFt",
            "ZRgCIAEoCRITCgtkZXNjcmlwdGlvbhgDIAEoCRJTChJjb25zdHJhaW50X2Rl",
            "ZmF1bHQYBCABKA4yNy5nb29nbGUuY2xvdWQub3JncG9saWN5LnYyLkNvbnN0",
            "cmFpbnQuQ29uc3RyYWludERlZmF1bHQSTwoPbGlzdF9jb25zdHJhaW50GAUg",
            "ASgLMjQuZ29vZ2xlLmNsb3VkLm9yZ3BvbGljeS52Mi5Db25zdHJhaW50Lkxp",
            "c3RDb25zdHJhaW50SAASVQoSYm9vbGVhbl9jb25zdHJhaW50GAYgASgLMjcu",
            "Z29vZ2xlLmNsb3VkLm9yZ3BvbGljeS52Mi5Db25zdHJhaW50LkJvb2xlYW5D",
            "b25zdHJhaW50SAAaPQoOTGlzdENvbnN0cmFpbnQSEwoLc3VwcG9ydHNfaW4Y",
            "ASABKAgSFgoOc3VwcG9ydHNfdW5kZXIYAiABKAgaEwoRQm9vbGVhbkNvbnN0",
            "cmFpbnQiTAoRQ29uc3RyYWludERlZmF1bHQSIgoeQ09OU1RSQUlOVF9ERUZB",
            "VUxUX1VOU1BFQ0lGSUVEEAASCQoFQUxMT1cQARIICgRERU5ZEAI6uAHqQbQB",
            "CiNvcmdwb2xpY3kuZ29vZ2xlYXBpcy5jb20vQ29uc3RyYWludBIrcHJvamVj",
            "dHMve3Byb2plY3R9L2NvbnN0cmFpbnRzL3tjb25zdHJhaW50fRIpZm9sZGVy",
            "cy97Zm9sZGVyfS9jb25zdHJhaW50cy97Y29uc3RyYWludH0SNW9yZ2FuaXph",
            "dGlvbnMve29yZ2FuaXphdGlvbn0vY29uc3RyYWludHMve2NvbnN0cmFpbnR9",
            "QhEKD2NvbnN0cmFpbnRfdHlwZULNAQodY29tLmdvb2dsZS5jbG91ZC5vcmdw",
            "b2xpY3kudjJCD0NvbnN0cmFpbnRQcm90b1ABWkJnb29nbGUuZ29sYW5nLm9y",
            "Zy9nZW5wcm90by9nb29nbGVhcGlzL2Nsb3VkL29yZ3BvbGljeS92Mjtvcmdw",
            "b2xpY3mqAhlHb29nbGUuQ2xvdWQuT3JnUG9saWN5LlYyygIZR29vZ2xlXENs",
            "b3VkXE9yZ1BvbGljeVxWMuoCHEdvb2dsZTo6Q2xvdWQ6Ok9yZ1BvbGljeTo6",
            "VjJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.OrgPolicy.V2.Constraint), global::Google.Cloud.OrgPolicy.V2.Constraint.Parser, new[]{ "Name", "DisplayName", "Description", "ConstraintDefault", "ListConstraint", "BooleanConstraint" }, new[]{ "ConstraintType" }, new[]{ typeof(global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ListConstraint), global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ListConstraint.Parser, new[]{ "SupportsIn", "SupportsUnder" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Cloud.OrgPolicy.V2.Constraint.Types.BooleanConstraint), global::Google.Cloud.OrgPolicy.V2.Constraint.Types.BooleanConstraint.Parser, null, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// A `constraint` describes a way to restrict resource's configuration. For
  /// example, you could enforce a constraint that controls which cloud services
  /// can be activated across an organization, or whether a Compute Engine instance
  /// can have serial port connections established. `Constraints` can be configured
  /// by the organization's policy administrator to fit the needs of the
  /// organization by setting a `policy` that includes `constraints` at different
  /// locations in the organization's resource hierarchy. Policies are inherited
  /// down the resource hierarchy from higher levels, but can also be overridden.
  /// For details about the inheritance rules please read about
  /// [`policies`][google.cloud.OrgPolicy.v2.Policy].
  ///
  /// `Constraints` have a default behavior determined by the `constraint_default`
  /// field, which is the enforcement behavior that is used in the absence of a
  /// `policy` being defined or inherited for the resource in question.
  /// </summary>
  public sealed partial class Constraint : pb::IMessage<Constraint>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Constraint> _parser = new pb::MessageParser<Constraint>(() => new Constraint());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Constraint> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Cloud.OrgPolicy.V2.ConstraintReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Constraint() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Constraint(Constraint other) : this() {
      name_ = other.name_;
      displayName_ = other.displayName_;
      description_ = other.description_;
      constraintDefault_ = other.constraintDefault_;
      switch (other.ConstraintTypeCase) {
        case ConstraintTypeOneofCase.ListConstraint:
          ListConstraint = other.ListConstraint.Clone();
          break;
        case ConstraintTypeOneofCase.BooleanConstraint:
          BooleanConstraint = other.BooleanConstraint.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Constraint Clone() {
      return new Constraint(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// Immutable. The resource name of the Constraint. Must be in one of
    /// the following forms:
    /// * `projects/{project_number}/constraints/{constraint_name}`
    /// * `folders/{folder_id}/constraints/{constraint_name}`
    /// * `organizations/{organization_id}/constraints/{constraint_name}`
    ///
    /// For example, "/projects/123/constraints/compute.disableSerialPortAccess".
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "display_name" field.</summary>
    public const int DisplayNameFieldNumber = 2;
    private string displayName_ = "";
    /// <summary>
    /// The human readable name.
    ///
    /// Mutable.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 3;
    private string description_ = "";
    /// <summary>
    /// Detailed description of what this `Constraint` controls as well as how and
    /// where it is enforced.
    ///
    /// Mutable.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "constraint_default" field.</summary>
    public const int ConstraintDefaultFieldNumber = 4;
    private global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault constraintDefault_ = global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault.Unspecified;
    /// <summary>
    /// The evaluation behavior of this constraint in the absence of 'Policy'.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault ConstraintDefault {
      get { return constraintDefault_; }
      set {
        constraintDefault_ = value;
      }
    }

    /// <summary>Field number for the "list_constraint" field.</summary>
    public const int ListConstraintFieldNumber = 5;
    /// <summary>
    /// Defines this constraint as being a ListConstraint.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ListConstraint ListConstraint {
      get { return constraintTypeCase_ == ConstraintTypeOneofCase.ListConstraint ? (global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ListConstraint) constraintType_ : null; }
      set {
        constraintType_ = value;
        constraintTypeCase_ = value == null ? ConstraintTypeOneofCase.None : ConstraintTypeOneofCase.ListConstraint;
      }
    }

    /// <summary>Field number for the "boolean_constraint" field.</summary>
    public const int BooleanConstraintFieldNumber = 6;
    /// <summary>
    /// Defines this constraint as being a BooleanConstraint.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Cloud.OrgPolicy.V2.Constraint.Types.BooleanConstraint BooleanConstraint {
      get { return constraintTypeCase_ == ConstraintTypeOneofCase.BooleanConstraint ? (global::Google.Cloud.OrgPolicy.V2.Constraint.Types.BooleanConstraint) constraintType_ : null; }
      set {
        constraintType_ = value;
        constraintTypeCase_ = value == null ? ConstraintTypeOneofCase.None : ConstraintTypeOneofCase.BooleanConstraint;
      }
    }

    private object constraintType_;
    /// <summary>Enum of possible cases for the "constraint_type" oneof.</summary>
    public enum ConstraintTypeOneofCase {
      None = 0,
      ListConstraint = 5,
      BooleanConstraint = 6,
    }
    private ConstraintTypeOneofCase constraintTypeCase_ = ConstraintTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ConstraintTypeOneofCase ConstraintTypeCase {
      get { return constraintTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearConstraintType() {
      constraintTypeCase_ = ConstraintTypeOneofCase.None;
      constraintType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Constraint);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Constraint other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (DisplayName != other.DisplayName) return false;
      if (Description != other.Description) return false;
      if (ConstraintDefault != other.ConstraintDefault) return false;
      if (!object.Equals(ListConstraint, other.ListConstraint)) return false;
      if (!object.Equals(BooleanConstraint, other.BooleanConstraint)) return false;
      if (ConstraintTypeCase != other.ConstraintTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (ConstraintDefault != global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault.Unspecified) hash ^= ConstraintDefault.GetHashCode();
      if (constraintTypeCase_ == ConstraintTypeOneofCase.ListConstraint) hash ^= ListConstraint.GetHashCode();
      if (constraintTypeCase_ == ConstraintTypeOneofCase.BooleanConstraint) hash ^= BooleanConstraint.GetHashCode();
      hash ^= (int) constraintTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DisplayName);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (ConstraintDefault != global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ConstraintDefault);
      }
      if (constraintTypeCase_ == ConstraintTypeOneofCase.ListConstraint) {
        output.WriteRawTag(42);
        output.WriteMessage(ListConstraint);
      }
      if (constraintTypeCase_ == ConstraintTypeOneofCase.BooleanConstraint) {
        output.WriteRawTag(50);
        output.WriteMessage(BooleanConstraint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DisplayName);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Description);
      }
      if (ConstraintDefault != global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ConstraintDefault);
      }
      if (constraintTypeCase_ == ConstraintTypeOneofCase.ListConstraint) {
        output.WriteRawTag(42);
        output.WriteMessage(ListConstraint);
      }
      if (constraintTypeCase_ == ConstraintTypeOneofCase.BooleanConstraint) {
        output.WriteRawTag(50);
        output.WriteMessage(BooleanConstraint);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (ConstraintDefault != global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ConstraintDefault);
      }
      if (constraintTypeCase_ == ConstraintTypeOneofCase.ListConstraint) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ListConstraint);
      }
      if (constraintTypeCase_ == ConstraintTypeOneofCase.BooleanConstraint) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BooleanConstraint);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Constraint other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.ConstraintDefault != global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault.Unspecified) {
        ConstraintDefault = other.ConstraintDefault;
      }
      switch (other.ConstraintTypeCase) {
        case ConstraintTypeOneofCase.ListConstraint:
          if (ListConstraint == null) {
            ListConstraint = new global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ListConstraint();
          }
          ListConstraint.MergeFrom(other.ListConstraint);
          break;
        case ConstraintTypeOneofCase.BooleanConstraint:
          if (BooleanConstraint == null) {
            BooleanConstraint = new global::Google.Cloud.OrgPolicy.V2.Constraint.Types.BooleanConstraint();
          }
          BooleanConstraint.MergeFrom(other.BooleanConstraint);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            DisplayName = input.ReadString();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 32: {
            ConstraintDefault = (global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault) input.ReadEnum();
            break;
          }
          case 42: {
            global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ListConstraint subBuilder = new global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ListConstraint();
            if (constraintTypeCase_ == ConstraintTypeOneofCase.ListConstraint) {
              subBuilder.MergeFrom(ListConstraint);
            }
            input.ReadMessage(subBuilder);
            ListConstraint = subBuilder;
            break;
          }
          case 50: {
            global::Google.Cloud.OrgPolicy.V2.Constraint.Types.BooleanConstraint subBuilder = new global::Google.Cloud.OrgPolicy.V2.Constraint.Types.BooleanConstraint();
            if (constraintTypeCase_ == ConstraintTypeOneofCase.BooleanConstraint) {
              subBuilder.MergeFrom(BooleanConstraint);
            }
            input.ReadMessage(subBuilder);
            BooleanConstraint = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            DisplayName = input.ReadString();
            break;
          }
          case 26: {
            Description = input.ReadString();
            break;
          }
          case 32: {
            ConstraintDefault = (global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ConstraintDefault) input.ReadEnum();
            break;
          }
          case 42: {
            global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ListConstraint subBuilder = new global::Google.Cloud.OrgPolicy.V2.Constraint.Types.ListConstraint();
            if (constraintTypeCase_ == ConstraintTypeOneofCase.ListConstraint) {
              subBuilder.MergeFrom(ListConstraint);
            }
            input.ReadMessage(subBuilder);
            ListConstraint = subBuilder;
            break;
          }
          case 50: {
            global::Google.Cloud.OrgPolicy.V2.Constraint.Types.BooleanConstraint subBuilder = new global::Google.Cloud.OrgPolicy.V2.Constraint.Types.BooleanConstraint();
            if (constraintTypeCase_ == ConstraintTypeOneofCase.BooleanConstraint) {
              subBuilder.MergeFrom(BooleanConstraint);
            }
            input.ReadMessage(subBuilder);
            BooleanConstraint = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Constraint message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Specifies the default behavior in the absence of any `Policy` for the
      /// `Constraint`. This must not be `CONSTRAINT_DEFAULT_UNSPECIFIED`.
      ///
      /// Immutable after creation.
      /// </summary>
      public enum ConstraintDefault {
        /// <summary>
        /// This is only used for distinguishing unset values and should never be
        /// used.
        /// </summary>
        [pbr::OriginalName("CONSTRAINT_DEFAULT_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// Indicate that all values are allowed for list constraints.
        /// Indicate that enforcement is off for boolean constraints.
        /// </summary>
        [pbr::OriginalName("ALLOW")] Allow = 1,
        /// <summary>
        /// Indicate that all values are denied for list constraints.
        /// Indicate that enforcement is on for boolean constraints.
        /// </summary>
        [pbr::OriginalName("DENY")] Deny = 2,
      }

      /// <summary>
      /// A `Constraint` that allows or disallows a list of string values, which are
      /// configured by an Organization's policy administrator with a `Policy`.
      /// </summary>
      public sealed partial class ListConstraint : pb::IMessage<ListConstraint>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<ListConstraint> _parser = new pb::MessageParser<ListConstraint>(() => new ListConstraint());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<ListConstraint> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Google.Cloud.OrgPolicy.V2.Constraint.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ListConstraint() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ListConstraint(ListConstraint other) : this() {
          supportsIn_ = other.supportsIn_;
          supportsUnder_ = other.supportsUnder_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ListConstraint Clone() {
          return new ListConstraint(this);
        }

        /// <summary>Field number for the "supports_in" field.</summary>
        public const int SupportsInFieldNumber = 1;
        private bool supportsIn_;
        /// <summary>
        /// Indicates whether values grouped into categories can be used in
        /// `Policy.allowed_values` and `Policy.denied_values`. For example,
        /// `"in:Python"` would match any value in the 'Python' group.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool SupportsIn {
          get { return supportsIn_; }
          set {
            supportsIn_ = value;
          }
        }

        /// <summary>Field number for the "supports_under" field.</summary>
        public const int SupportsUnderFieldNumber = 2;
        private bool supportsUnder_;
        /// <summary>
        /// Indicates whether subtrees of Cloud Resource Manager resource hierarchy
        /// can be used in `Policy.allowed_values` and `Policy.denied_values`. For
        /// example, `"under:folders/123"` would match any resource under the
        /// 'folders/123' folder.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool SupportsUnder {
          get { return supportsUnder_; }
          set {
            supportsUnder_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as ListConstraint);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(ListConstraint other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (SupportsIn != other.SupportsIn) return false;
          if (SupportsUnder != other.SupportsUnder) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (SupportsIn != false) hash ^= SupportsIn.GetHashCode();
          if (SupportsUnder != false) hash ^= SupportsUnder.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (SupportsIn != false) {
            output.WriteRawTag(8);
            output.WriteBool(SupportsIn);
          }
          if (SupportsUnder != false) {
            output.WriteRawTag(16);
            output.WriteBool(SupportsUnder);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (SupportsIn != false) {
            output.WriteRawTag(8);
            output.WriteBool(SupportsIn);
          }
          if (SupportsUnder != false) {
            output.WriteRawTag(16);
            output.WriteBool(SupportsUnder);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (SupportsIn != false) {
            size += 1 + 1;
          }
          if (SupportsUnder != false) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(ListConstraint other) {
          if (other == null) {
            return;
          }
          if (other.SupportsIn != false) {
            SupportsIn = other.SupportsIn;
          }
          if (other.SupportsUnder != false) {
            SupportsUnder = other.SupportsUnder;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                SupportsIn = input.ReadBool();
                break;
              }
              case 16: {
                SupportsUnder = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                SupportsIn = input.ReadBool();
                break;
              }
              case 16: {
                SupportsUnder = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

      }

      /// <summary>
      /// A `Constraint` that is either enforced or not.
      ///
      /// For example a constraint `constraints/compute.disableSerialPortAccess`.
      /// If it is enforced on a VM instance, serial port connections will not be
      /// opened to that instance.
      /// </summary>
      public sealed partial class BooleanConstraint : pb::IMessage<BooleanConstraint>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<BooleanConstraint> _parser = new pb::MessageParser<BooleanConstraint>(() => new BooleanConstraint());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<BooleanConstraint> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Google.Cloud.OrgPolicy.V2.Constraint.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BooleanConstraint() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BooleanConstraint(BooleanConstraint other) : this() {
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public BooleanConstraint Clone() {
          return new BooleanConstraint(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as BooleanConstraint);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(BooleanConstraint other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(BooleanConstraint other) {
          if (other == null) {
            return;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
