name: Check that apis.json is valid JSON

on: [pull_request, push]

permissions: {}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        persist-credentials: false

    - name: Validate API catalog
      run: python -c 'import json; json.load(open("generator-input/apis.json", "r"))'
