name: Check that all pre and post-generation scripts are executable

on: [pull_request, push]

permissions: {}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        persist-credentials: false

    - name: Validate script permissions
      run: '! stat -c "%a %n" generator-input/tweaks/*/p*.sh | grep -v 755'
