name: Run Storage Retry conformance tests against service emulator

on:
  push:
    branches: [ main ]
    paths:
    - 'apis/Google.Cloud.Storage.V1/**'
  pull_request:
    paths:
    - 'apis/Google.Cloud.Storage.V1/**'

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/google-cloud-dotnet/google-cloud-dotnet/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.RetryConformanceTests/

    services:
      emulator:
        image: gcr.io/cloud-devrel-public-resources/storage-testbench@sha256:600fa5c3cfc8be26435c38591cc094fb4ef648f760ffabf77f93237b1ebee027
        ports:
          - 9000:9000

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        submodules: true
        persist-credentials: false

    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - run: dotnet test Google.Cloud.Storage.V1.RetryConformanceTests.csproj
      env:
        TEST_BENCH_URL: http://localhost:9000/
