name: Run Storage Retry conformance tests against service emulator

on:
  push:
    branches: [ main ]
    paths:
    - 'apis/Google.Cloud.Storage.V1/**'
  pull_request:
    paths:
    - 'apis/Google.Cloud.Storage.V1/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/google-cloud-dotnet/google-cloud-dotnet/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.RetryConformanceTests/

    services:
      emulator:
        image: gcr.io/cloud-devrel-public-resources/storage-testbench:latest
        ports:
          - 9000:9000

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - run: dotnet test Google.Cloud.Storage.V1.RetryConformanceTests.csproj
      env:
        TEST_BENCH_URL: http://localhost:9000/
